<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * invoices — one invoice per clinic per month. Generated by the monthly
 * billing job (Step 6) on the 1st; ACH debit runs on the 10th. Immutable
 * financial record — NOT soft-deletable.
 *
 * `period` is YYYY-MM string; unique per (clinicId, period).
 * `status` lifecycle: draft -> sent -> paying -> paid | failed | overdue.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('invoices', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('number', 40)->unique();          // "RC-2026-04-C1"
            $table->uuid('clinicId');
            $table->string('period', 7);                     // "2026-04"
            $table->string('status', 20)->default('draft');  // draft | sent | paying | paid | failed | overdue
            $table->decimal('subtotal', 12, 2)->default(0);
            $table->decimal('tax', 12, 2)->default(0);
            $table->decimal('total', 12, 2)->default(0);
            $table->unsignedInteger('claimCount')->default(0);
            $table->unsignedInteger('aiCount')->default(0);
            $table->unsignedInteger('fullServiceCount')->default(0);
            $table->date('invoiceDate');                     // 1st of month
            $table->date('dueDate');                         // 10th of month (ACH debit day)
            $table->timestamp('sentAt')->nullable();
            $table->timestamp('paidAt')->nullable();
            $table->string('billingMethod', 10)->default('ach'); // BillingMethod enum: ach | card
            $table->uuid('pdfFileId')->nullable();           // -> files.id for the rendered PDF
            $table->timestamp('createdAt')->nullable();
            $table->timestamp('updatedAt')->nullable();

            $table->foreign('clinicId')
                ->references('id')
                ->on('clinics')
                ->restrictOnDelete();                        // don't cascade — keep financial record

            $table->foreign('pdfFileId')
                ->references('id')
                ->on('files')
                ->nullOnDelete();

            $table->unique(['clinicId', 'period']);
            $table->index('clinicId');
            $table->index(['clinicId', 'period']);           // launcher-required compound index
            $table->index('status');
            $table->index('dueDate');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('invoices');
    }
};
